packages:
  - name: app
    type: yarn
    srcs:
      - "package.json"
      - "tsconfig.json"
      - "yarn.lock"
      - "src/**/*.ts"
    config:
      packaging: app
      dontTest: true
      yarnlock: "yarn.lock"
      tsconfig: "tsconfig.json"
  
  - name: docker
    type: docker
    deps:
      - :app
    srcs:
      - "Dockerfile"
    config:
      dockerfile: Dockerfile
      image:
        - localhost:5000/hello-world-ts
