packages:
  - name: app
    type: yarn
    srcs:
      - "package.json"
      - "tsconfig.json"
      - "package-lock.json"
      - "src/**/*.ts"
    config:
      packaging: app
      dontTest: true
      yarnlock: "package-lock.json"
      tsconfig: "tsconfig.json"
  
  - name: docker
    type: docker
    deps:
      - :app
    srcs:
      - "Dockerfile"
    config:
      dockerfile: Dockerfile
      image: 
        - ts-hello-world
