packages:
  - name: all
    type: generic
    deps:
      - components/go-hello-world:app
      - components/ts-hello-world:app
      - components/go-hello-world:docker
      - components/ts-hello-world:docker
    config:
      commands:
        - ["echo", "Built both Go and TypeScript projects and their Docker images"]
