packages:
  - name: all
    type: generic
    deps:
      - components/go-hello-world:docker
      - components/ts-hello-world:docker
    config:
      commands:
        - ["echo", "Built both Go and TypeScript projects"]
