packages:
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    config:
      packaging: app
      dontTest: false
  
  - name: docker
    type: docker
    deps:
      - :app
    srcs:
      - "Dockerfile"
    config:
      dockerfile: Dockerfile
      image:
        - localhost:5000/hello-world-go
